import {describe,it,expect,vi,afterEach} from "vitest";
import {decodeDraft,draftKey,readDrafts,saveDraft,clearDrafts,DRAFT_TTL,type SavedRecordDraft} from "../src/lib/record-draft";
import {photoDimensions,uploadPreparedPhoto,preparePhoto,PHOTO_UPLOAD_LIMIT} from "../src/lib/photo-upload";
const now=Date.now(),mapId="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const sample:SavedRecordDraft={format:1,updatedAt:now,mapId,editingId:null,editingVersion:null,configRevision:1,draft:{title:"미완성 기록",body:"관찰 내용",categoryKey:"",emojiKey:"",ratingKey:"",location:"",idea:"",imageName:"사진.jpg",link:"",answers:{}},coordinates:{lat:37.5,lng:127},source:"manual",step:1,request:{key:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",payload:"{}"},savedPointId:null};
class MemoryStorage implements Storage{items=new Map<string,string>();get length(){return this.items.size;}clear(){this.items.clear();}getItem(k:string){return this.items.get(k)??null;}key(i:number){return [...this.items.keys()][i]??null;}removeItem(k:string){this.items.delete(k);}setItem(k:string,v:string){this.items.set(k,v);}}
afterEach(()=>vi.unstubAllGlobals());
describe("record recovery",()=>{
 it("restores location and retry identity without keeping a photo blob or credential",()=>{const restored=decodeDraft(JSON.stringify({...sample,csrfToken:"not-for-storage",photo:{data:"bytes"}}),now);expect(restored).toEqual(sample);});
 it("rejects expired, malformed and invalid coordinates",()=>{expect(decodeDraft(JSON.stringify(sample),now+DRAFT_TTL)).toBeNull();expect(decodeDraft("{" )).toBeNull();expect(decodeDraft(JSON.stringify({...sample,coordinates:{lat:100,lng:0}}),now)).toBeNull();});
 it("isolates accounts, maps and edit drafts; logout clears only app drafts",()=>{const storage=new MemoryStorage();saveDraft(storage,"user-a",sample);saveDraft(storage,"user-b",{...sample,draft:{...sample.draft,title:"다른 계정"}});saveDraft(storage,"user-a",{...sample,editingId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"});storage.setItem("unrelated","keep");expect(readDrafts(storage,"user-a",mapId)).toHaveLength(2);expect(readDrafts(storage,"user-b",mapId)[0].draft.title).toBe("다른 계정");expect(readDrafts(storage,"user-a","dddddddd-dddd-4ddd-8ddd-dddddddddddd")).toEqual([]);clearDrafts(storage);expect(storage.length).toBe(1);});
 it("purges tampered key bindings and preserves storage errors for caller",()=>{const storage=new MemoryStorage();storage.setItem(draftKey("a",mapId,null),JSON.stringify({...sample,editingId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"}));expect(readDrafts(storage,"a",mapId)).toEqual([]);expect(storage.length).toBe(0);storage.setItem=()=>{throw new Error("quota");};expect(()=>saveDraft(storage,"a",sample)).toThrow("quota");});
});
describe("photo preparation",()=>{
 it("fits portrait and landscape without upscaling and bounds huge images",()=>{expect(photoDimensions(4000,3000)).toEqual({width:1600,height:1200});expect(photoDimensions(1000,2000)).toEqual({width:800,height:1600});expect(photoDimensions(320,240)).toEqual({width:320,height:240});expect(()=>photoDimensions(10000,10000)).toThrow();});
 it("rejects excessive files and unsupported formats before decoding",async()=>{await expect(preparePhoto(new File([new Uint8Array(20*1024*1024+1)],"large.jpg",{type:"image/jpeg"}))).rejects.toThrow("20MB");await expect(preparePhoto(new File(["<svg/>"],"x.svg",{type:"image/svg+xml"}))).rejects.toThrow("JPG");});
});
class FakeXHR{
 static latest:FakeXHR;upload:{onprogress?:(e:{lengthComputable:boolean;loaded:number;total:number})=>void;onload?:()=>void}={};status=201;responseText='{"data":{"photoUrl":"/photo","status":"published","version":"2"}}';timeout=0;onload=()=>{};onerror=()=>{};ontimeout=()=>{};onabort=()=>{};headers:Record<string,string>={};constructor(){FakeXHR.latest=this;}open(){}setRequestHeader(k:string,v:string){this.headers[k]=v;}send(){}
}
describe("photo transport",()=>{
 it("reports bytes sent separately from server completion",async()=>{vi.stubGlobal("XMLHttpRequest",FakeXHR);const progress:number[]=[];const pending=uploadPreparedPhoto("/photo",new File(["x"],"x.jpg",{type:"image/jpeg"}),"csrf",p=>progress.push(p));const xhr=FakeXHR.latest;xhr.upload.onprogress?.({lengthComputable:true,loaded:1,total:2});xhr.upload.onload?.();expect(progress).toEqual([0,50,100]);expect(xhr.timeout).toBe(90000);xhr.onload();expect((await pending).version).toBe("2");});
 it("handles non-JSON hosting errors, expiry and disconnection",async()=>{vi.stubGlobal("XMLHttpRequest",FakeXHR);for(const status of [413,401,503]){const pending=uploadPreparedPhoto("/photo",new File(["x"],"x.jpg"),"csrf",()=>{});FakeXHR.latest.status=status;FakeXHR.latest.responseText="upstream error";FakeXHR.latest.onload();await expect(pending).rejects.toMatchObject({status});}const pending=uploadPreparedPhoto("/photo",new File(["x"],"x.jpg"),"csrf",()=>{});FakeXHR.latest.onerror();await expect(pending).rejects.toThrow("연결이 끊겼습니다");});
 it("never sends an uncompressed oversized body",async()=>{vi.stubGlobal("XMLHttpRequest",FakeXHR);await expect(uploadPreparedPhoto("/photo",new File([new Uint8Array(PHOTO_UPLOAD_LIMIT+1)],"x.jpg"),"csrf",()=>{})).rejects.toThrow("크기를 줄여");});
});
