"use client";
import {useEffect,useState} from "react";
import type {GameSummary} from "@/domain/exploration-game";
import {GameShell,GameMessage,gameRequest,useGameSession} from "./GameShared";
import {GameJoinForm} from "./GameJoinForm";
export default function GameDirectory(){
  const {session,ready,error:sessionError}=useGameSession();const [games,setGames]=useState<GameSummary[]>([]),[deleted,setDeleted]=useState<GameSummary[]>([]),[q,setQ]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{if(!ready)return;const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);void fetch(`/api/v1/games?q=${encodeURIComponent(q)}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message??"목록을 불러오지 못했어요.");setGames(p.data.items);setError("");}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},q?250:0);return()=>{clearTimeout(timer);controller.abort();};},[ready,q]);
  useEffect(()=>{if(!ready||session?.kind!=="account")return;let active=true;void gameRequest<{items:GameSummary[]}>("/api/v1/games?scope=deleted").then(r=>{if(active)setDeleted(r.items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[ready,session?.kind]);
  return <GameShell title="탐험게임" back="/"><section className="game-intro"><span className="quest-tag">🎮 동네가 게임이 되는 순간!</span><h1>미션을 찾고<br/>탐험 배지를 모아 봐!</h1><p>선생님이 연 게임방에 들어가 장소를 찾고 미션을 해결해요.</p></section><GameMessage error={error||sessionError}/><GameJoinForm session={session} ready={ready}/><section className="game-section"><h2>탐험게임맵 목록</h2><label className="game-field">게임맵 검색<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="게임맵 이름으로 찾아요" maxLength={80}/></label>{loading?<p role="status">게임맵을 불러오고 있어요…</p>:!games.length?<p className="game-empty">아직 보이는 게임맵이 없어요. 방 코드가 있다면 위에서 참여할 수 있어요.</p>:<div className="game-catalog">{games.map(g=><a key={g.id} href={`/games/${g.id}`} className="game-card"><span className="game-card-icon">🗺️</span><div><strong>{g.title}</strong><small>{g.location} · 포인트 {g.pointCount}곳 · 미션 {g.missionCount}개</small><small>{g.status==="archived"?"보관 중":g.canManage?"교사 · 게임방 열기 및 미션 제작":"학생 · 방 코드로 참여"}</small></div><span aria-hidden="true">›</span></a>)}</div>}</section>{!!deleted.length&&<section className="game-section"><h2>삭제한 게임맵</h2><p>삭제 후 30일 안에 복구할 수 있어요.</p>{deleted.map(g=><a className="game-card" key={g.id} href={`/games/${g.id}`}><span>🗑️</span><span><strong>{g.title}</strong><small>삭제일 {new Date(g.deletedAt!).toLocaleDateString("ko-KR")} · 복구하기</small></span></a>)}</section>}<aside className="game-tip"><strong>교사가 새 게임맵을 만들려면</strong><p>기존 지도에 들어가 <b>탐험 가방 → 탐험게임맵 제작</b>을 눌러 주세요. 원본 기록은 바뀌지 않아요.</p>{session?.kind==="account"&&!session.accountRole&&<a href="/account/setup?returnTo=%2Fgames">회원 유형 선택하기</a>}{!session&&<a href="/api/v1/auth/google?returnTo=%2Fgames">교사 Google 로그인</a>}</aside></GameShell>;
}
