"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import KakaoMap,{type MapFocus,type MapPoint} from "@/components/KakaoMap";
import {gameDistance,arrivalFailure,missionLabels,type RoomState,type GameMission,type GameSubmission} from "@/domain/exploration-game";
import {GameShell,GameMessage,gameRequest,useGameSession} from "./GameShared";
type Position={lat:number;lng:number;accuracy:number;observedAt:string};
const stateLabel:Record<GameSubmission["status"],string>={approved:"완료",pending:"교사 승인 대기",incorrect:"다시 도전",rejected:"보완 후 다시 제출"};
function freshPosition():Promise<Position>{return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error("이 기기에서는 위치를 확인할 수 없어요."));return;}navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,observedAt:new Date(p.timestamp).toISOString()}),e=>reject(new Error(e.code===1?"브라우저의 위치 권한을 허용해 주세요.":"위치를 확인하지 못했어요. 야외에서 다시 시도해 주세요.")),{enableHighAccuracy:true,timeout:12000,maximumAge:0});});}
export default function GameRoom({roomId}:{roomId:string}){
  const {session,ready,error:sessionError}=useGameSession();const [data,setData]=useState<RoomState|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[clock,setClock]=useState(Date.now());
  const [selected,setSelected]=useState<string|null>(null),[choice,setChoice]=useState<number|undefined>(),[answer,setAnswer]=useState(""),[checks,setChecks]=useState<number[]>([]),[position,setPosition]=useState<Position|null>(null),[gpsError,setGpsError]=useState("");
  const [focus,setFocus]=useState<MapFocus|null>(null),[reasons,setReasons]=useState<Record<string,string>>({}),[confirmEnd,setConfirmEnd]=useState(false),[offset,setOffset]=useState(0),[visible,setVisible]=useState(true);const centered=useRef(false),retry=useRef<{key:string;id:string}|null>(null);
  const base=`/api/v1/game-rooms/${roomId}`;
  const load=useCallback(async()=>{const next=await gameRequest<RoomState>(base);setOffset(new Date(next.room.serverNow).getTime()-Date.now());setData(next);},[base]);
  useEffect(()=>{if(!ready)return;if(!session){setError("방 코드로 먼저 참여해 주세요.");return;}let active=true;const refresh=()=>{if(!active||document.hidden)return;void gameRequest<RoomState>(base).then(next=>{if(active){setData(next);setOffset(new Date(next.room.serverNow).getTime()-Date.now());}}).catch(e=>{if(active)setError(e.message);});};refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer);};},[base,ready,session]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const room=data?.room;const end=room?.endsAt?new Date(room.endsAt).getTime():null;const ended=room?.status==="ended"||(room?.status==="running"&&end!==null&&clock+offset>=end);
  const remaining=end===null?null:Math.min(room!.durationMinutes*60,Math.max(0,Math.ceil((end-clock-offset)/1000)));
  const watching=!!data?.me?.sharing&&!room?.isHost&&!ended;
  useEffect(()=>{function onVisibility(){setVisible(!document.hidden);if(!document.hidden)void load().catch(()=>{});}document.addEventListener("visibilitychange",onVisibility);setVisible(!document.hidden);return()=>document.removeEventListener("visibilitychange",onVisibility);},[load]);
  useEffect(()=>{
    if(!watching||!visible||!session?.csrfToken)return;
    if(!navigator.geolocation){setGpsError("이 기기에서는 위치를 확인할 수 없어요.");return;}
    let active=true,inFlight=false,lastSent=0;setGpsError("");
    function stopSharing(){if(!active)return;void fetch(base,{method:"POST",keepalive:true,headers:{"Content-Type":"application/json","X-CSRF-Token":session!.csrfToken!},body:JSON.stringify({action:"stop_sharing"})}).catch(()=>{});}
    function onHide(){if(document.hidden)stopSharing();}window.addEventListener("pagehide",stopSharing);document.addEventListener("visibilitychange",onHide);
    async function receive(p:GeolocationPosition){if(!active||document.hidden)return;const pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,observedAt:new Date(p.timestamp).toISOString()};setPosition(pos);
      if(!centered.current){centered.current=true;setFocus({location:pos,nonce:Date.now()});}
      if(inFlight||Date.now()-lastSent<4000)return;inFlight=true;lastSent=Date.now();try{await gameRequest(base+"/location",session!.csrfToken,{location:{lat:pos.lat,lng:pos.lng},accuracy:pos.accuracy,observedAt:pos.observedAt});if(active)setGpsError("");}catch(e){if(active)setGpsError(e instanceof Error?e.message:"위치 공유가 끊겼어요.");}finally{inFlight=false;}}
    function failed(e:GeolocationPositionError){if(active)setGpsError(e.code===1?"위치 권한이 꺼져 있어요. 브라우저에서 허용한 뒤 다시 위치를 확인해 주세요.":"위치를 확인하는 중이에요. 야외에서 다시 시도해 주세요.");}
    const options={enableHighAccuracy:true,timeout:12000,maximumAge:5000};const watch=navigator.geolocation.watchPosition(p=>void receive(p),failed,options);
    const heartbeat=setInterval(()=>{if(active&&!document.hidden)navigator.geolocation.getCurrentPosition(p=>void receive(p),failed,{...options,maximumAge:0});},15000);
    return()=>{active=false;navigator.geolocation.clearWatch(watch);clearInterval(heartbeat);window.removeEventListener("pagehide",stopSharing);document.removeEventListener("visibilitychange",onHide);setPosition(null);};
  },[watching,visible,session?.csrfToken,base]);
  async function act(body:unknown,message:string){if(busy)return;setBusy(true);setError("");try{await gameRequest(base,session?.csrfToken??null,body);await load();setNotice(message);}catch(e){setError(e instanceof Error?e.message:"처리하지 못했어요.");}finally{setBusy(false);}}
  function choose(m:GameMission){setSelected(m.id);setChoice(undefined);setAnswer("");setChecks([]);retry.current=null;setNotice("");setFocus({location:m.location,radiusMeters:m.radiusMeters,nonce:Date.now()});}
  useEffect(()=>{if(selected)document.getElementById("student-mission")?.scrollIntoView({behavior:"smooth",block:"nearest"});},[selected]);
  const mission=data?.missions.find(m=>m.id===selected)??null;const ownSubmission=data?.submissions.find(s=>s.missionId===selected&&s.playerId===data.me?.id);
  const arrival=mission?arrivalFailure(position?{...position,observedAt:new Date(position.observedAt)}:null,mission,new Date(clock+offset)):null;
  const locked=!!ownSubmission&&(ownSubmission.status==="approved"||ownSubmission.status==="pending"||ownSubmission.attempts>= (mission?.maxAttempts??0));
  async function submit(e:FormEvent){e.preventDefault();if(busy||!mission||!data?.me)return;setBusy(true);setError("");setNotice("");try{
    const gps=await freshPosition();setPosition(gps);await gameRequest(base+"/location",session?.csrfToken??null,{location:{lat:gps.lat,lng:gps.lng},accuracy:gps.accuracy,observedAt:gps.observedAt});
    const response=mission.kind==="quiz"?{choice}:mission.kind==="checklist"?{checks,answer}:{answer};const key=JSON.stringify({missionId:mission.id,response});if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};
    const result=await gameRequest<GameSubmission>(base+"/submissions",session?.csrfToken??null,{missionId:mission.id,response,requestId:retry.current.id});
    setNotice(result.status==="approved"?`미션 완료! ${result.score}점을 획득했어요. 다음 포인트로 탐험을 이어 가요.`:result.status==="pending"?"응답을 제출했어요. 선생님이 승인하면 점수를 받아요.":`다시 생각해 보세요! ${Math.max(0,mission.maxAttempts-result.attempts)}번의 기회가 남았어요.`);retry.current=null;await load();
  }catch(e){setError(e instanceof Error?e.message:"제출하지 못했어요.");}finally{setBusy(false);}}
  const points:MapPoint[]=[];const pointSeen=new Set<string>();data?.missions.forEach(m=>{if(pointSeen.has(m.pointId))return;pointSeen.add(m.pointId);const completed=data.missions.filter(x=>x.pointId===m.pointId).every(x=>data.submissions.some(s=>s.playerId===data.me?.id&&s.missionId===x.id&&s.status==="approved"));points.push({id:`mission:${m.pointId}`,title:m.pointTitle,emoji:completed?"🏅":m.emoji,color:completed?"#267253":"#e7ae32",location:m.location});});
  if(!ended&&room?.isHost)data?.players.forEach(p=>{if(p.location)points.push({id:`player:${p.id}`,title:`${p.nickname} · 위치 오차 ${Math.round(p.location.accuracy)}m`,emoji:"🧑",color:"#3b77c1",location:p.location});});
  if(!ended&&!room?.isHost&&position&&watching)points.push({id:"me",title:"나의 현재 위치",emoji:"🧭",color:"#3b77c1",location:position});
  return <GameShell title={room?.title??"게임방"} back="/games"><GameMessage error={error||sessionError} notice={notice}/>{!data?<section className="game-section"><p role="status">게임방을 확인하고 있어요…</p><a href="/games">방 코드로 참여하기</a></section>:<>
    <div className={`game-hud ${ended?"game-hud--ended":""}`}><span><small>{ended?"탐험 종료":room?.status==="lobby"?"출발 준비":"남은 시간"}</small><strong role="timer" aria-label="게임 남은 시간">{ended?"🏁 완료":remaining===null?`${room!.durationMinutes}분`:`${String(Math.floor(remaining/60)).padStart(2,"0")}:${String(remaining%60).padStart(2,"0")}`}</strong></span><span><small>{room!.isHost?"참여 학생":"나의 점수"}</small><strong>{room!.isHost?`${data.players.length}/${room!.maxPlayers}`:`${data.me?.score??0}점`}</strong></span><span><small>{room!.isHost?"미션":"완료 미션"}</small><strong>{room!.isHost?`${data.missions.length}개`:`${data.me?.completed??0}/${data.missions.length}`}</strong></span></div>
    {room!.isHost&&!ended&&<section className="game-room-code"><small>학생에게 알려 줄 게임방 코드</small><strong>{room!.joinCode}</strong><div className="game-actions"><button type="button" className="button button--light" onClick={()=>void navigator.clipboard.writeText(room!.joinCode??"").then(()=>setNotice("방 코드를 복사했어요.")).catch(()=>setError("복사가 허용되지 않았어요. 위 코드를 직접 알려 주세요."))}>코드 복사</button><button type="button" className="button button--light" onClick={()=>void navigator.clipboard.writeText(new URL(`/games#code=${encodeURIComponent(room!.joinCode??"")}`,location.origin).href).then(()=>setNotice("게임 참여 링크를 복사했어요.")).catch(()=>setError("링크를 복사하지 못했어요."))}>참여 링크 복사</button>{room!.status==="lobby"?<button type="button" className="button button--primary" disabled={busy||!data.players.length} onClick={()=>void act({action:"start"},"탐험게임을 시작했어요!")}>탐험게임 시작</button>:<button type="button" className="button button--light" onClick={()=>setConfirmEnd(true)}>게임 조기 종료</button>}</div>{confirmEnd&&<div className="game-tip"><p>지금 종료하면 새 미션을 제출할 수 없고 위치 공유도 중지됩니다.</p><button type="button" disabled={busy} onClick={()=>{void act({action:"end"},"게임을 종료했어요.");setConfirmEnd(false);}}>게임 종료 확인</button><button type="button" onClick={()=>setConfirmEnd(false)}>취소</button></div>}<p className="game-help">대기 방은 생성 후 2시간 동안 입장할 수 있어요. 게임이 시작되면 제한시간 동안만 입장할 수 있어요.</p></section>}
    {!room!.isHost&&!ended&&<section className="game-location-status"><p>{data.me?.sharing?"🧭 이 방의 교사에게만 위치를 공유 중이에요.":"⏸ 위치 공유가 꺼져 있어요."}</p>{gpsError&&<p role="status">{gpsError}</p>}<div className="game-actions"><button type="button" disabled={busy} onClick={()=>void act({action:data.me?.sharing?"stop_sharing":"resume_sharing"},data.me?.sharing?"위치 공유를 중지했어요.":"교사에게 위치를 공유해요.")}>{data.me?.sharing?"위치 공유 끄기":"교사에게 위치 공유 시작"}</button>{data.me?.sharing&&<button type="button" onClick={()=>void freshPosition().then(p=>{setPosition(p);setFocus({location:p,nonce:Date.now()});setGpsError("");}).catch(e=>setGpsError(e.message))}>내 위치 다시 확인</button>}</div><small>화면을 나가거나 숨기면 공유를 중지해요. 돌아와서 다시 켜 주세요.</small></section>}
    {ended&&<section className="game-results"><span>🏆</span><h1>탐험 완료! 순위를 확인해요</h1><p>게임이 종료되었어요. 위치 공유와 새 제출은 중지됐습니다.</p>{data.pendingCount>0&&<p className="game-tip">교사 승인 대기 {data.pendingCount}건이 있어요. 아래는 현재 승인 점수의 순위이며 검토 후 갱신됩니다.</p>}</section>}
    <div className="game-room-grid"><section><div className="game-live-map" id="game-room-map"><KakaoMap autoLocate={false} center={data.missions[0]?.location} points={points} focus={focus} selectedId={mission?`mission:${mission.pointId}`:null} onSelectPoint={id=>{if(id.startsWith("mission:")){const m=data.missions.find(m=>m.pointId===id.slice(8));if(m)choose(m);}else if(id.startsWith("player:")){const p=data.players.find(p=>p.id===id.slice(7));if(p?.location)setFocus({location:p.location,nonce:Date.now()});}}}/></div>
    <section className="game-section"><h2>{room!.isHost?"게임 미션":"탐험할 미션"}</h2><div className="game-mission-buttons">{data.missions.map(m=>{const s=data.submissions.find(s=>s.playerId===data.me?.id&&s.missionId===m.id);return <button type="button" key={m.id} className={selected===m.id?"selected":""} onClick={()=>choose(m)}><span>{s?.status==="approved"?"🏅":m.emoji}</span><span><strong>{m.title}</strong><small>{m.pointTitle} · {m.points}점{position?` · ${Math.round(gameDistance(position,m.location))}m 떨어짐`:""}</small><small>{s?stateLabel[s.status]:missionLabels[m.kind]}</small></span></button>;})}</div></section>
    {mission&&!room!.isHost&&<section className="game-section game-answer" id="student-mission"><span className="game-badge">{missionLabels[mission.kind]} · {mission.points}점</span><h2>{mission.title}</h2><p className="game-prompt">{mission.prompt}</p><p className="game-help">장소 반경 {mission.radiusMeters}m 안에서 수행해요. 제출 {ownSubmission?.attempts??0}/{mission.maxAttempts}회</p>{ownSubmission&&<p className="game-tip">{stateLabel[ownSubmission.status]} {ownSubmission.score>0?`· ${ownSubmission.score}점`:""}{ownSubmission.reason&&<><br/>선생님 의견: {ownSubmission.reason}</>}</p>}{!ended&&!locked&&<form onSubmit={submit}><fieldset disabled={busy||room!.status!=="running"}><legend className="sr-only">미션 응답</legend>{mission.kind==="quiz"?mission.options.map((o,i)=><label className="game-choice" key={i}><input type="radio" required name={`mission-${mission.id}`} checked={choice===i} onChange={()=>setChoice(i)}/>{o}</label>):mission.kind==="checklist"?<>{mission.checklist.map((item,i)=><label className="game-choice" key={i}><input type="checkbox" required checked={checks.includes(i)} onChange={e=>setChecks(e.target.checked?[...checks,i]:checks.filter(x=>x!==i))}/>{item}</label>)}<label className="game-field">관찰 메모 (선택)<textarea value={answer} maxLength={1500} onChange={e=>setAnswer(e.target.value)} rows={3}/></label></>:<label className="game-field">{mission.kind==="short_answer"?"퀴즈 답":"현장에서 관찰한 내용"}<textarea required maxLength={1500} value={answer} onChange={e=>setAnswer(e.target.value)} rows={4}/></label>}<p role="status" className="game-help">{room!.status==="lobby"?"선생님이 게임을 시작하면 도전할 수 있어요.":!data.me?.sharing?"위치 공유를 켜 주세요.":arrival??"미션 장소에 도착했어요! 응답을 제출해 보세요."}</p><button className="button button--primary button--full" type="submit" disabled={!!arrival||!data.me?.sharing}>{busy?"위치와 응답을 확인 중…":"미션 응답 제출"}</button></fieldset></form>}</section>}
    </section><aside><section className="game-section game-leaderboard"><h2>{ended?"🏆 게임 순위":"탐험 점수판"}</h2>{!data.players.length?<p>학생들이 방 코드로 참여하면 여기에 보여요.</p>:<ol>{data.players.map(p=><li key={p.id} className={p.id===data.me?.id?"is-me":""}><b>{p.rank}위</b><span><strong>{p.nickname}{p.id===data.me?.id?" (나)":""}</strong><small>미션 {p.completed}개 완료{room!.isHost&&!ended?` · ${p.location?`위치 ${Math.max(0,Math.floor((clock+offset-new Date(p.location.observedAt).getTime())/1000))}초 전 · 오차 ${Math.round(p.location.accuracy)}m`:p.sharing?"위치 확인 대기":"공유 중지"}`:""}</small></span><em>{p.score}점</em>{room!.isHost&&p.location&&<button type="button" aria-label={`${p.nickname} 위치 보기`} onClick={()=>{setFocus({location:p.location!,nonce:Date.now()});document.getElementById("game-room-map")?.scrollIntoView({behavior:"smooth",block:"start"});}}>📍</button>}</li>)}</ol>}<p className="game-help">동점은 공동 순위입니다. 이동 속도는 점수에 반영하지 않아요.</p></section>
    {room!.isHost&&<section className="game-section"><h2>학생 응답 검토 {data.pendingCount}건</h2>{data.submissions.filter(s=>s.status==="pending").map(s=>{const m=data.missions.find(m=>m.id===s.missionId),p=data.players.find(p=>p.id===s.playerId);return <article key={s.id} className="game-review"><strong>{p?.nickname} · {m?.title}</strong>{m?.kind==="checklist"?<ul>{s.response.checks?.map(i=><li key={i}>{m.checklist[i]}</li>)}</ul>:null}<p className="game-student-response">{s.response.answer||"체크리스트를 제출했어요."}</p><label className="game-field">{p?.nickname} 응답에 대한 의견<textarea maxLength={500} rows={2} value={reasons[s.id]??""} onChange={e=>setReasons({...reasons,[s.id]:e.target.value})} placeholder="보완 요청에는 이유를 적어 주세요"/></label><div className="game-actions"><button type="button" disabled={busy} className="button button--primary" onClick={()=>void act({action:"review",submissionId:s.id,version:s.version,decision:"approve",reason:reasons[s.id]??""},"응답을 승인하고 점수를 부여했어요.")}>승인 · {m?.points}점</button><button type="button" disabled={busy||(reasons[s.id]?.trim().length??0)<2} className="button button--light" onClick={()=>void act({action:"review",submissionId:s.id,version:s.version,decision:"reject",reason:reasons[s.id]??""},"보완 의견을 전달했어요.")}>보완 요청</button></div></article>;})}{!data.pendingCount&&<p className="game-empty">검토 대기 응답이 없습니다.</p>}</section>}
    </aside></div><footer className="game-section"><a className="button button--light" href={room!.isHost?`/games/${room!.gameId}`:"/games"}>{room!.isHost?"게임맵 제작 화면으로":"탐험게임 목록으로"}</a></footer>
  </>}</GameShell>;
}
