"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {GameShell,GameMessage,useGameSession,gameRequest} from "./GameShared";
export default function GameCreator({sourceMapId}:{sourceMapId:string}){
  const {session,ready,error:sessionError}=useGameSession();const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[sourceTitle,setSourceTitle]=useState(""),[allowed,setAllowed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const requestId=useRef<string|null>(null);
  useEffect(()=>{if(!ready)return;let active=true;void gameRequest<{title:string;capabilities:{canManageMap:boolean};status:string}>(`/api/v1/maps/${sourceMapId}`).then(m=>{if(active){setSourceTitle(m.title);setTitle(`${m.title} 탐험게임`.slice(0,80));setAllowed(m.capabilities.canManageMap&&session?.accountRole==="teacher"&&m.status==="active");}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[ready,sourceMapId,session?.accountRole]);
  async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{requestId.current??=crypto.randomUUID();const game=await gameRequest<{id:string}>("/api/v1/games",session?.csrfToken??null,{sourceMapId,title,description,requestId:requestId.current});window.location.assign(`/games/${game.id}`);}catch(e){setError(e instanceof Error?e.message:"만들지 못했어요.");setBusy(false);}}
  return <GameShell title="탐험게임맵 제작" back={`/?map=${encodeURIComponent(sourceMapId)}`}><section className="game-section"><h1>우리 지도를<br/>미션 탐험으로!</h1><p><b>{sourceTitle||"기존 지도"}</b>의 게시된 위치 포인트를 복사해 게임맵을 만들어요. 원본 지도는 바뀌지 않아요. 승인 대기·숨김·삭제 기록은 복사하지 않습니다.</p><GameMessage error={error||sessionError}/>{!ready?<p>로그인을 확인하고 있어요…</p>:!allowed?<div className="game-tip"><p>교사로 가입한 운영 중인 지도의 개설자 또는 관리자만 제작할 수 있어요.</p>{session?.kind==="account"&&!session.accountRole&&<a href={`/account/setup?returnTo=${encodeURIComponent(`/games/new?source=${sourceMapId}`)}`}>회원 유형 선택하기</a>}</div>:<form onSubmit={create}><label className="game-field">게임맵 이름<input required minLength={2} maxLength={80} value={title} onChange={e=>{setTitle(e.target.value);requestId.current=null;}}/></label><label className="game-field">탐험 이야기와 안내<textarea maxLength={500} rows={4} value={description} onChange={e=>{setDescription(e.target.value);requestId.current=null;}} placeholder="예: 모두에게 편리한 길을 찾는 탐험대가 되어 보자!"/></label><button className="button button--primary button--full" disabled={busy} type="submit">{busy?"포인트를 복사하고 있어요…":"이 지도로 게임맵 만들기"}</button></form>}</section></GameShell>;
}
