"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import KakaoMap,{type Coordinates} from "@/components/KakaoMap";
import {missionLabels,missionKinds,type GameDefinition,type GameMission,type MissionKind} from "@/domain/exploration-game";
import {GameShell,GameMessage,gameRequest,useGameSession} from "./GameShared";
import GameOwnerDelete from "./GameOwnerDelete";
import {GameJoinForm} from "./GameJoinForm";
type Form={id?:string;pointId:string;title:string;prompt:string;kind:MissionKind;points:number;radiusMeters:number;maxAttempts:number;options:string;answers:string;checklist:string};
const blank=(pointId:string):Form=>({pointId,title:"",prompt:"",kind:"quiz",points:100,radiusMeters:50,maxAttempts:3,options:"",answers:"0",checklist:""});
const split=(s:string)=>s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
export default function GameEditor({gameId}:{gameId:string}){
  const {session,ready,error:sessionError}=useGameSession();const [game,setGame]=useState<GameDefinition|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<string|null>(null),[form,setForm]=useState<Form>(blank("")),[q,setQ]=useState("");
  const [showPoint,setShowPoint]=useState(false),[pointTitle,setPointTitle]=useState(""),[emoji,setEmoji]=useState("📍"),[position,setPosition]=useState<Coordinates|null>(null);
  const [roomTitle,setRoomTitle]=useState("우리 반 탐험게임"),[minutes,setMinutes]=useState(30),[maxPlayers,setMaxPlayers]=useState(40),[name,setName]=useState(""),[description,setDescription]=useState("");const roomRequest=useRef<string|null>(null);
  const load=useCallback(async()=>{const g=await gameRequest<GameDefinition>(`/api/v1/games/${gameId}`);setGame(g);setName(g.title);setDescription(g.description);setForm(old=>old.pointId?old:blank(g.points[0]?.id??""));},[gameId]);
  useEffect(()=>{if(ready)void load().catch(e=>setError(e.message));},[ready,load]);
  async function mutate(body:Record<string,unknown>,done:string){if(busy||!game)return false;setBusy(true);setError("");setNotice("");try{await gameRequest(`/api/v1/games/${gameId}`,session?.csrfToken??null,{...body,version:game.version});await load();setNotice(done);return true;}catch(e){setError(e instanceof Error?e.message:"저장하지 못했어요.");return false;}finally{setBusy(false);}}
  function edit(m:GameMission){setForm({id:m.id,pointId:m.pointId,title:m.title,prompt:m.prompt,kind:m.kind,points:m.points,radiusMeters:m.radiusMeters,maxAttempts:m.maxAttempts,options:m.options.join("\n"),answers:m.correctAnswers?.join("\n")??"",checklist:m.checklist.join("\n")});setSelected(m.pointId);document.getElementById("mission-editor")?.scrollIntoView({behavior:"smooth"});}
  async function save(e:FormEvent){e.preventDefault();const mission={pointId:form.pointId,title:form.title,prompt:form.prompt,kind:form.kind,points:form.points,radiusMeters:form.radiusMeters,maxAttempts:form.maxAttempts,options:form.kind==="quiz"?split(form.options):[],correctAnswers:form.kind==="quiz"?[form.answers]:form.kind==="short_answer"?split(form.answers):[],checklist:form.kind==="checklist"?split(form.checklist):[]};if(await mutate({action:"mission",...(form.id?{id:form.id}:{}),mission},"미션을 저장했어요."))setForm(blank(form.pointId));}
  async function addPoint(e:FormEvent){e.preventDefault();if(!position)return;if(await mutate({action:"point",point:{title:pointTitle,emoji,location:position}},"게임 전용 포인트를 추가했어요.")){setShowPoint(false);setPointTitle("");setPosition(null);}}
  async function openRoom(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{roomRequest.current??=crypto.randomUUID();const r=await gameRequest<{id:string}>(`/api/v1/games/${gameId}/rooms`,session?.csrfToken??null,{title:roomTitle,durationMinutes:minutes,maxPlayers,requestId:roomRequest.current});window.location.assign(`/games/rooms/${r.id}`);}catch(e){setError(e instanceof Error?e.message:"게임방을 만들지 못했어요.");setBusy(false);}}
  const active=game?.status==="active";
  return <GameShell title={game?.title??"게임맵 불러오기"}><GameMessage error={error||sessionError} notice={notice}/>{!game?<section className="game-section"><p role="status">게임맵을 불러오고 있어요…</p><button type="button" onClick={()=>void load().catch(e=>setError(e.message))}>다시 불러오기</button></section>:game.status==="deleted"?<><section className="game-section"><h1>{game.title}</h1><p>삭제한 게임맵입니다.</p></section><GameOwnerDelete game={game} csrfToken={session?.csrfToken??null} onChanged={load}/></>:!game.canManage?<><section className="game-section"><h1>{game.title}</h1><p>{game.description}</p><p>미션 {game.missionCount}개 · {game.location}</p><p>선생님이 알려 준 게임방 코드로 참여해 주세요.</p></section><GameJoinForm session={session} ready={ready}/><GameOwnerDelete game={game} csrfToken={session?.csrfToken??null} onChanged={load}/></>:<>
  <section className="game-section"><span className="quest-tag">교사 제작 화면</span><h1>장소마다 미션을 준비해요</h1><p>게임 포인트 {game.pointCount}곳이에요. 게임방을 만들면 미션과 점수를 복사해 고정하고, 이후 수정은 새 방부터 반영합니다.</p><a href={`/?map=${game.sourceMapId}`}>원본 지도 보기 ↗</a></section>
  <div className="game-edit-map"><KakaoMap autoLocate={false} center={game.points[0]?.location} points={game.points.map(p=>({id:p.id,title:p.title,emoji:p.emoji,color:game.missions.some(m=>m.pointId===p.id)?"#E8AB32":"#267253",location:p.location}))} selectedId={selected} onSelectPoint={id=>{setSelected(id);setForm(blank(id));document.getElementById("mission-editor")?.scrollIntoView({behavior:"smooth"});}}/></div>
  {active&&<section className="game-section"><button type="button" className="button button--light button--full" onClick={()=>setShowPoint(!showPoint)}>📍 새 위치 포인트 {showPoint?"닫기":"등록하기"}</button>{showPoint&&<form onSubmit={addPoint} className="game-point-form"><p>게임맵에만 추가됩니다. 안전하게 머무를 수 있는 장소를 선택해 주세요.</p><KakaoMap compact autoLocate={false} center={game.points[0]?.location} onPick={p=>setPosition(p)} chosen={position}/><label className="game-field">새 포인트 이름<input required maxLength={80} value={pointTitle} onChange={e=>setPointTitle(e.target.value)}/></label><label className="game-field">대표 이모지<input required maxLength={16} value={emoji} onChange={e=>setEmoji(e.target.value)}/></label><p className="game-help">{position?`선택 위치 ${position.lat.toFixed(5)}, ${position.lng.toFixed(5)}`:"지도를 누르거나 장소를 검색해 위치를 선택해 주세요."}</p><button className="button button--primary" disabled={busy||!position}>포인트 등록</button></form>}</section>}
  {active&&<section className="game-section game-mission-editor" id="mission-editor"><h2>{form.id?"미션 수정":"미션 추가"}</h2><form onSubmit={save}><label className="game-field">포인트 찾기<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="포인트 이름"/></label><label className="game-field">미션 장소<select required value={form.pointId} onChange={e=>{setForm({...form,pointId:e.target.value});setSelected(e.target.value);}}><option value="">장소를 골라 주세요</option>{game.points.filter(p=>p.id===form.pointId||!q||p.title.includes(q)).map(p=><option key={p.id} value={p.id}>{p.emoji} {p.title}</option>)}</select></label>
  <label className="game-field">미션 종류<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as MissionKind,answers:e.target.value==="quiz"?"0":""})}>{missionKinds.map(k=><option key={k} value={k}>{missionLabels[k]}</option>)}</select></label><button type="button" className="button button--light" onClick={()=>setForm({...form,title:"이 장소의 특징 찾기",prompt:"현장에서 발견한 특징 두 가지와 더 좋게 바꿀 아이디어 한 가지를 적어 주세요.",kind:"observation",answers:"",options:"",checklist:""})}>관찰 미션 예시 넣기</button>
  <label className="game-field">미션 제목<input required minLength={2} maxLength={80} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="game-field">문제 또는 수행 안내<textarea required minLength={2} maxLength={1500} rows={4} value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})}/></label>
  {form.kind==="quiz"&&<><label className="game-field">객관식 보기 (2~6개, 한 줄에 하나)<textarea required rows={4} value={form.options} onChange={e=>setForm({...form,options:e.target.value})}/></label><label className="game-field">정답 보기<select value={form.answers} onChange={e=>setForm({...form,answers:e.target.value})}>{split(form.options).map((o,i)=><option key={i} value={String(i)}>{i+1}. {o}</option>)}</select></label></>}
  {form.kind==="short_answer"&&<label className="game-field">인정할 정답 (한 줄에 하나)<textarea required rows={3} value={form.answers} onChange={e=>setForm({...form,answers:e.target.value})}/><small>띄어쓰기와 영문 대소문자 차이는 무시합니다.</small></label>}
  {form.kind==="checklist"&&<label className="game-field">확인할 항목 (1~10개, 한 줄에 하나)<textarea required rows={4} value={form.checklist} onChange={e=>setForm({...form,checklist:e.target.value})}/></label>}
  {(form.kind==="observation"||form.kind==="checklist")&&<p className="game-tip">학생 응답은 교사 승인 후 점수를 받습니다.</p>}
  <div className="game-form-grid"><label className="game-field">완료 점수<input type="number" required min={1} max={1000} value={form.points} onChange={e=>setForm({...form,points:Number(e.target.value)})}/></label><label className="game-field">도착 반경 (m)<input type="number" required min={20} max={500} value={form.radiusMeters} onChange={e=>setForm({...form,radiusMeters:Number(e.target.value)})}/></label><label className="game-field">최대 제출 횟수<input type="number" required min={1} max={10} value={form.maxAttempts} onChange={e=>setForm({...form,maxAttempts:Number(e.target.value)})}/></label></div><div className="game-actions"><button className="button button--primary" disabled={busy||!form.pointId}>{form.id?"미션 수정 저장":"미션 추가 저장"}</button>{form.id&&<button type="button" className="button button--light" onClick={()=>setForm(blank(form.pointId))}>수정 취소</button>}</div></form></section>}
  <section className="game-section"><h2>등록한 미션 {game.missions.length}개</h2>{!game.missions.length&&<p className="game-empty">포인트를 선택하고 첫 미션을 만들어 주세요.</p>}{game.missions.map(m=><article className="game-mission-card" key={m.id}><small>{m.emoji} {m.pointTitle} · {missionLabels[m.kind]}</small><h3>{m.title}</h3><p>{m.prompt}</p><span className="game-badge">{m.points}점 · 반경 {m.radiusMeters}m · {m.maxAttempts}회</span>{active&&<div className="game-actions"><button type="button" className="button button--light" onClick={()=>edit(m)}>미션 수정</button><details><summary>미션 삭제</summary><p>새 방에서 제외됩니다. 이미 만든 방의 미션은 유지돼요.</p><button type="button" disabled={busy} onClick={()=>void mutate({action:"delete_mission",id:m.id},"미션을 삭제했어요.")}>이 미션 삭제 확인</button></details></div>}</article>)}</section>
  {active&&<section className="game-section game-room-create"><h2>🎮 게임방 만들기</h2><p>학생들이 들어오면 교사가 시작 버튼을 누릅니다.</p><form onSubmit={openRoom}><label className="game-field">게임방 이름<input required minLength={2} maxLength={80} value={roomTitle} onChange={e=>{setRoomTitle(e.target.value);roomRequest.current=null;}}/></label><div className="game-form-grid"><label className="game-field">제한시간 (분)<input type="number" required min={1} max={180} value={minutes} onChange={e=>{setMinutes(Number(e.target.value));roomRequest.current=null;}}/></label><label className="game-field">최대 참여 인원<input type="number" required min={1} max={200} value={maxPlayers} onChange={e=>{setMaxPlayers(Number(e.target.value));roomRequest.current=null;}}/></label></div><button className="button button--primary button--full" disabled={busy||!game.missions.length}>{busy?"처리 중…":"게임방 열고 방 코드 만들기"}</button></form></section>}
  {!!game.rooms.length&&<section className="game-section"><h2>내가 연 게임방</h2>{game.rooms.map(r=><a key={r.id} className="game-card" href={`/games/rooms/${r.id}`}><span>🎮</span><span><strong>{r.title}</strong><small>{r.status==="lobby"?"시작 대기":r.status==="running"?"진행 중":"종료 · 결과 보기"}</small></span><span>›</span></a>)}</section>}
  <section className="game-section"><details><summary>게임맵 이름과 보관 설정</summary><label className="game-field">게임맵 이름<input maxLength={80} minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label className="game-field">설명<textarea maxLength={500} value={description} onChange={e=>setDescription(e.target.value)}/></label><button type="button" disabled={busy} className="button button--light" onClick={()=>void mutate({action:"settings",title:name,description,status:game.status},"설정을 저장했어요.")}>이름과 설명 저장</button><p>게임맵을 보관하면 진행 중인 방도 종료됩니다.</p><button type="button" disabled={busy} className="button button--light" onClick={()=>void mutate({action:"settings",title:name,description,status:active?"archived":"active"},"게임맵 상태를 변경했어요.")}>{active?"게임맵 보관":"게임맵 다시 운영"}</button></details></section>
  <GameOwnerDelete game={game} csrfToken={session?.csrfToken??null} onChanged={load}/></>}</GameShell>;
}
