"use client";
import {useState,type FormEvent} from "react";
import {accountRoles,accountRoleLabels,type AccountRole} from "@/domain/account";
import {GameShell,GameMessage,gameRequest,useGameSession} from "./games/GameShared";
export default function AccountSetup({returnTo}:{returnTo:string}){
 const {session,ready,error:sessionError}=useGameSession();const [role,setRole]=useState<AccountRole|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();if(!role||busy)return;setBusy(true);setError("");try{await gameRequest("/api/v1/account",session?.csrfToken??null,{role});location.assign(returnTo);}catch(e){setError(e instanceof Error?e.message:"회원가입을 완료하지 못했어요.");setBusy(false);}}
 return <GameShell title="회원 유형 선택" back="/" sectionLabel="회원가입"><section className="game-section"><span className="quest-tag">🧭 탐험대 회원가입</span><h1>어떤 탐험대원인가요?</h1><p>교사는 일반 지도와 탐험게임맵을 만들 수 있어요. 학생과 일반회원은 지도에 참여하고 기록을 남길 수 있어요.</p><GameMessage error={error||sessionError}/>{!ready?<p role="status">회원 정보를 확인하고 있어요…</p>:session?.kind!=="account"?<a className="button button--primary" href={`/api/v1/auth/google?returnTo=${encodeURIComponent(`/account/setup?returnTo=${encodeURIComponent(returnTo)}`)}`}>Google 로그인하고 가입하기</a>:session.accountRole?<><p className="game-tip">{accountRoleLabels[session.accountRole]}로 가입되어 있어요. 가입한 회원 유형은 이 화면에서 변경할 수 없습니다.</p><a className="button button--primary" href={returnTo}>돌아가기</a></>:<form onSubmit={submit}><fieldset disabled={busy}><legend>회원 유형</legend>{accountRoles.map(r=><label className="game-choice" key={r}><input type="radio" required name="account-role" value={r} checked={role===r} onChange={()=>setRole(r)}/><span><strong>{r==="teacher"?"👩‍🏫":r==="student"?"🎒":"🧭"} {accountRoleLabels[r]}</strong><small style={{display:"block",marginTop:6}}>{r==="teacher"?"지도 만들기·수업 탐험게임 운영":"지도 참여·관찰 기록·미션 수행"}</small></span></label>)}<p className="game-help">회원 유형은 가입할 때 한 번 선택합니다.</p><button className="button button--primary button--full" disabled={!role}>{busy?"가입 정보를 저장 중…":"선택한 유형으로 회원가입 완료"}</button></fieldset></form>}</section></GameShell>;
}
