"use client";
import {useState} from "react";
import type {Theme} from "@/lib/demo-data";
import {filterLabel,type AnalysisStats,type CountOption,type ObservationFilter} from "@/domain/analysis";

export type AnalysisData={stats:AnalysisStats;dataRevision:string;generatedAt:string;filterFingerprint:string;filter:ObservationFilter};
type FilterProps={theme:Theme;filter:ObservationFilter;onChange:(filter:ObservationFilter)=>void;bounds?:ObservationFilter["bbox"]};
export function AnalysisFilters({theme,filter,onChange,bounds}:FilterProps){
  const change=(key:"category"|"rating"|"from"|"to",value:string)=>{const next={...filter};if(value)next[key]=value;else delete next[key];onChange(next);};
  return <details className="analysis-filters"><summary>조건 선택 <span>{filterLabel(filter,theme)}</span></summary><div className="analysis-filter-grid"><label>유형<select value={filter.category??""} onChange={e=>change("category",e.target.value)}><option value="">모든 유형</option>{theme.categories.map(c=><option key={c.key} value={c.key}>{c.emojiOptions[0]?.glyph} {c.label}</option>)}</select></label>{theme.features.ratingEnabled&&theme.rating&&<label>{theme.rating.label}<select value={filter.rating??""} onChange={e=>change("rating",e.target.value)}><option value="">모든 평가</option>{theme.rating.options.map(r=><option key={r.key} value={r.key}>{r.symbol} {r.label}</option>)}</select></label>}<label>시작일<input type="date" value={filter.from??""} max={filter.to} onChange={e=>change("from",e.target.value)}/></label><label>종료일<input type="date" value={filter.to??""} min={filter.from} onChange={e=>change("to",e.target.value)}/></label></div><p className="help-text">등록일 기준 · 한국 시간 · 지도·목록·분석에 함께 적용됩니다.</p><div className="analysis-actions">{bounds&&<button type="button" onClick={()=>onChange({...filter,bbox:bounds})}>현재 보이는 지도 영역</button>}<button type="button" onClick={()=>onChange({})}>조건 초기화</button>{filter.question&&<button type="button" onClick={()=>{const next={...filter};delete next.question;delete next.answer;onChange(next);}}>질문 조건 해제</button>}</div></details>;
}
export function CountChart({title,options,onSelect,note}:{title:string;options:CountOption[];onSelect?:(key:string)=>void;note?:string}){
  return <section className="chart-card analysis-chart"><h2>{title}</h2>{note&&<p className="help-text">{note}</p>}<ul>{options.map(o=><li key={o.key}><button type="button" disabled={!onSelect} onClick={()=>onSelect?.(o.key)}><span>{o.glyph} {o.label}</span><strong>{o.count}건 <small>{o.percent===null?"—":`${o.percent}%`}</small></strong><span className="analysis-bar" aria-hidden="true"><i style={{width:`${o.percent??0}%`,backgroundColor:o.color??"#287554"}}/></span></button></li>)}</ul></section>;
}
export function AnalysisPanel({theme,filter,onChange,bounds,data,loading,error,mapId,csrfToken,canExport,onShowRecords,onRefresh}:{theme:Theme;filter:ObservationFilter;onChange:(filter:ObservationFilter)=>void;bounds?:ObservationFilter["bbox"];data:AnalysisData|null;loading:boolean;error:string;mapId:string;csrfToken?:string|null;canExport:boolean;onShowRecords:()=>void;onRefresh:()=>void}){
  const [includeAuthor,setIncludeAuthor]=useState(false),[includeCoordinates,setIncludeCoordinates]=useState(false),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState("");
  async function download(){setExporting(true);setExportError("");try{const response=await fetch(`/api/v1/maps/${mapId}/exports`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken??""},body:JSON.stringify({filter,includeAuthor,includeCoordinates})});if(!response.ok){const result=await response.json();throw new Error(result.error?.message??"내보내지 못했습니다.");}const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="우리동네-기록.csv";link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setExportError(e instanceof Error?e.message:"내보내지 못했습니다.");}finally{setExporting(false);}}
  const select=(next:ObservationFilter)=>{onChange(next);onShowRecords();};
  const stats=data?.stats;
  return <div className="content-scroll"><section className="content-heading"><span className="eyebrow">OUR DATA</span><h1>우리가 발견한<br/><em>동네 이야기</em></h1><p>기록을 함께 살펴보고 변화를 제안해요.</p></section><AnalysisFilters theme={theme} filter={filter} onChange={onChange} bounds={bounds}/>{loading?<p role="status">기록과 통계를 불러오는 중…</p>:error?<div className="analysis-error" role="alert">{error}<button type="button" onClick={onRefresh}>다시 불러오기</button></div>:stats&&<><div className="stat-hero"><span>이 조건에 맞는 게시 기록</span><strong>{stats.total.toLocaleString()}<small>건</small></strong><p>{stats.firstDay?`${stats.firstDay} ~ ${stats.lastDay}`:"아직 기록이 없어요"}</p></div><div className="analysis-actions"><button type="button" onClick={onShowRecords}>이 기록을 목록으로 보기</button><button type="button" onClick={onRefresh}>새로 집계</button></div><CountChart title="유형별 기록" options={stats.byCategory} onSelect={category=>select({...filter,category})}/>{stats.byRating&&<CountChart title={`${theme.rating?.label} 분포`} options={stats.byRating.map(option=>({...option,glyph:theme.rating?.options.find(rating=>rating.key===option.key)?.symbol}))} note={`유효 응답 ${stats.ratedCount}건 기준 · 제외 ${stats.ratingExcludedCount}건`} onSelect={rating=>select({...filter,rating})}/>}<section className="chart-card"><h2>날짜별 기록</h2><p className="help-text">등록일 기준 · 막대를 누르면 그날의 기록을 확인해요.</p><div className="daily-chart">{stats.byDay.map(d=><button type="button" key={d.day} onClick={()=>select({...filter,from:d.day,to:d.day})}><span>{d.day}</span><meter min={0} max={Math.max(...stats.byDay.map(v=>v.count),1)} value={d.count}>{d.count}</meter><strong>{d.count}건</strong></button>)}{!stats.byDay.length&&<p>표시할 기록이 없습니다.</p>}</div></section>{stats.questions.map(q=><CountChart key={`${q.configRevision}:${q.key}`} title={q.label} options={q.options} note={`설정 ${q.configRevision} · 유효 응답 ${q.answeredCount}건 · 확인 못함 ${q.unknownCount} · 해당 없음 ${q.notApplicableCount} · 미응답 ${q.missingCount}${q.multiple?" · 복수 선택으로 합계가 100%를 넘을 수 있어요.":""}`} onSelect={answer=>select({...filter,question:q.key,answer})}/>)}<p className="help-text">{new Date(data.generatedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})} 집계. 같은 장소의 반복 관찰도 각각 1건입니다. 기록 수는 시설 수나 동네 전체의 안전 점수가 아닙니다.</p></>}{canExport&&<section className="chart-card"><h2>기록 내려받기</h2><p className="help-text">같은 필터의 게시 기록을 CSV로 저장합니다. 본문에 적힌 개인정보도 확인해 주세요.</p><label className="analysis-check"><input type="checkbox" checked={includeAuthor} onChange={e=>setIncludeAuthor(e.target.checked)}/>작성자 닉네임 포함</label><label className="analysis-check"><input type="checkbox" checked={includeCoordinates} onChange={e=>setIncludeCoordinates(e.target.checked)}/>장소·정밀 좌표 포함</label><button className="button button--light button--full" type="button" disabled={loading||!!error||exporting} onClick={()=>void download()}>{exporting?"준비 중…":"CSV 내려받기"}</button>{exportError&&<p role="alert">{exportError}</p>}</section>}</div>;
}
